import { useEffect, useRef, useState } from 'react';
import { compileExpression } from '@zynth/shared';

/**
 * The Intuition figure: what you predicted, against what actually happens.
 *
 * This is not an illustration of the product — it is the product's own maths.
 * The curves are generated by the same `compileExpression` evaluator the app
 * renders with, from the same kind of expression Gemini emits for a real
 * Intuition spec. Projectile range at three launch angles, which is very close
 * to what the live model actually produces for a physics node.
 *
 * Colour follows the app's rule exactly: cyan is reality, violet-dashed is the
 * student's guess. Red/amber/green are reserved for mastery everywhere in this
 * product, so they never appear here — a wrong prediction is not a red node,
 * it is a wrong prediction.
 *
 * Both curves draw themselves in on scroll via stroke-dashoffset, the guess
 * first, so the eye reads "here is what I thought" before "here is what is".
 */

const W = 860;
const H = 360;
const PAD = { l: 30, r: 30, t: 26, b: 40 };
const PLOT_W = W - PAD.l - PAD.r;
const PLOT_H = H - PAD.t - PAD.b;

const DOMAIN: [number, number] = [0, 20];
const RANGE: [number, number] = [0, 6];
const SAMPLES = 160;

/** Projectile height vs horizontal distance for a launch angle, in degrees. */
const TRAJECTORY = 'x * tan(t * pi / 180) - 0.05 * x^2 / cos(t * pi / 180)^2';

/** The truth (45°, maximum range) and the common wrong guess (60°, "steeper must be further"). */
const TRUTH_ANGLE = 45;
const GUESS_ANGLE = 60;

function buildPath(angle: number): string {
  const fn = compileExpression(TRAJECTORY, ['x', 't']);
  if (!fn) return '';

  const [x0, x1] = DOMAIN;
  const [y0, y1] = RANGE;
  let d = '';
  let pen = false;

  for (let i = 0; i <= SAMPLES; i += 1) {
    const x = x0 + ((x1 - x0) * i) / SAMPLES;
    const y = fn.evaluate(x, angle);

    // Stop at the ground rather than plotting below it — a projectile that has
    // landed has no trajectory left, and a curve diving off the axis reads as a
    // bug rather than as physics.
    if (!Number.isFinite(y) || y < y0) {
      pen = false;
      continue;
    }

    const px = PAD.l + (PLOT_W * (x - x0)) / (x1 - x0);
    const py = PAD.t + PLOT_H * (1 - (y - y0) / (y1 - y0));
    d += `${pen ? 'L' : 'M'}${px.toFixed(1)} ${py.toFixed(1)} `;
    pen = true;
  }
  return d.trim();
}

/** Where a trajectory returns to the ground — used to mark the range reached. */
function landingX(angle: number): number {
  const fn = compileExpression(TRAJECTORY, ['x', 't']);
  if (!fn) return PAD.l;
  const [x0, x1] = DOMAIN;
  let last = x0;
  for (let i = 1; i <= SAMPLES; i += 1) {
    const x = x0 + ((x1 - x0) * i) / SAMPLES;
    const y = fn.evaluate(x, angle);
    if (Number.isFinite(y) && y >= RANGE[0]) last = x;
    else break;
  }
  return PAD.l + (PLOT_W * (last - x0)) / (x1 - x0);
}

export function Predict() {
  const ref = useRef<SVGSVGElement>(null);
  const [on, setOn] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      setOn(true);
      return;
    }
    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          setOn(true);
          io.disconnect();
        }
      },
      { threshold: 0.3 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const groundY = PAD.t + PLOT_H;
  const truthLand = landingX(TRUTH_ANGLE);
  const guessLand = landingX(GUESS_ANGLE);

  return (
    <svg
      ref={ref}
      viewBox={`0 0 ${W} ${H}`}
      className="predict"
      role="img"
      aria-label="A predicted projectile path at sixty degrees falling short of the true maximum range at forty-five degrees."
      data-on={on}
    >
      {/* ground */}
      <line x1={PAD.l} y1={groundY} x2={W - PAD.r} y2={groundY} stroke="var(--s-line)" strokeWidth="1.5" />

      {/* the guess, drawn first */}
      <path
        d={buildPath(GUESS_ANGLE)}
        fill="none"
        stroke="var(--violet)"
        strokeWidth="2"
        strokeDasharray="7 5"
        strokeLinecap="round"
        className="pr-path pr-guess"
      />
      {/* reality */}
      <path
        d={buildPath(TRUTH_ANGLE)}
        fill="none"
        stroke="var(--cyan)"
        strokeWidth="2.8"
        strokeLinecap="round"
        className="pr-path pr-truth"
      />

      {/* where each one lands — the whole point, side by side */}
      <g className="pr-marks">
        <circle cx={guessLand} cy={groundY} r="4" fill="var(--violet)" />
        <text x={guessLand} y={groundY + 22} textAnchor="middle" className="pr-label" data-tone="guess">
          your guess
        </text>
        <circle cx={truthLand} cy={groundY} r="5" fill="var(--cyan)" />
        <text x={truthLand} y={groundY + 22} textAnchor="middle" className="pr-label" data-tone="truth">
          furthest
        </text>
      </g>
    </svg>
  );
}
